version: '3.8'
services: 
    certbot:
        image: certbot/certbot
        command: certonly --webroot --webroot-path=/var/www/certbot --email blabla@mail.com --agree-tos --no-eff-email -d localhost.com
        volumes: 
            -   ./nginx/certbot/conf:/etc/letsencrypt
            -   ./nginx/certbot/www:/var/www/certbot
